export const LIST_ALL_CUSTOMERS_SUCCESS =  'LIST_ALL_CUSTOMERS_SUCCESS';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';

export const SEARCH_ALL_CUSTOMERS_SUCCESS = 'SEARCH_ALL_CUSTOMERS_SUCCESS';
